"""add ml feature columns to students

Revision ID: 918e54ac77c7
Revises: bb5160228ecb
Create Date: 2026-05-08 03:33:52.587324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918e54ac77c7'
down_revision: Union[str, Sequence[str], None] = 'bb5160228ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('famrel', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('freetime', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('goout', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('dalc', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('walc', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('health', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('medu', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('fedu', sa.Integer(), nullable=True))
    op.drop_column('students', 'internet_access')
    op.drop_column('students', 'extra_support')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('extra_support', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('internet_access', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('students', 'fedu')
    op.drop_column('students', 'medu')
    op.drop_column('students', 'health')
    op.drop_column('students', 'walc')
    op.drop_column('students', 'dalc')
    op.drop_column('students', 'goout')
    op.drop_column('students', 'freetime')
    op.drop_column('students', 'famrel')
    # ### end Alembic commands ###
